## Numpy - the hero you never new you needed

In [16]:
#1/[1, 2, 3, 4, 5, 6, 7]

Like matplotlib We need to install a the numpy library to do that run the following command. 

In [3]:
#!pip install --user numpy
#Windows python -m pip install --user numpy*
#!pip install --user numpy
#Windows python -m pip install --user numpy*
!pip install --user numpy

   ---------------------------------------- 0.0/12.6 MB ? eta -:--:--
   ---------------------- ----------------- 7.1/12.6 MB 39.4 MB/s eta 0:00:01
   ---------------------------------------- 12.6/12.6 MB 38.3 MB/s eta 0:00:00


  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.

[notice] A new release of pip is available: 25.0.1 -> 25.1
[notice] To update, run: C:\Users\OGrex\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\python.exe -m pip install --upgrade pip


In [18]:
import numpy as np
#By convention, NumPy is imported as np.

# One D

In [ ]:
npList = np.array([1, 2, 3, 4, 5, 6])
print(npList)
print(type(npList))


[1 2 3 4 5 6]
<class 'numpy.ndarray'>


## creating a vector

In [20]:
zeros = np.zeros(10) #creates an array of 10 zeros
ones = np.ones(10) #creates an array of 10 ones
twos = np.full(10, 2) #creates an array of 10 twos
random_array = np.random.randint(0,10,size=5)# Creating an array with 5 elements and random values from 0 to 9

print("\nZero array\n",zeros)
print("\nOnes array\n",ones)
print("\nTwos array\n",twos)
print("Random array:\n", random_array)



Zero array
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]

Ones array
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]

Twos array
 [2 2 2 2 2 2 2 2 2 2]
Random array:
 [5 3 2 1 0]


## Basic Operations

In [21]:
print(1/npList) #True Division
print(1//npList) # Floor Division
print(2*npList)
print(npList+npList)
print(npList-npList)
print(npList*npList)
print(npList/npList) #True Division
print(npList//npList) #Floor Division
print(npList%npList) #Modulus
print(npList**npList) #Exponentiation


[1.         0.5        0.33333333 0.25       0.2        0.16666667]
[1 0 0 0 0 0]
[ 2  4  6  8 10 12]
[ 2  4  6  8 10 12]
[0 0 0 0 0 0]
[ 1  4  9 16 25 36]
[1. 1. 1. 1. 1. 1.]
[1 1 1 1 1 1]
[0 0 0 0 0 0]
[    1     4    27   256  3125 46656]


In [22]:
npList.ndim # the dementions of the list
print("The dementions of the list is: ", npList.ndim)

npList.shape # the shape of the list
print("The shape of the list is: ", npList.shape)

npList.size # the size of the list
print("The size of the list is: ", npList.size)

npList.dtype # the data type of the list
print("The data type of the list is: ", npList.dtype)

npList.itemsize # the size of each element in the list
print("The size of each element in the list is: ", npList.itemsize)

npList.nbytes # the total size of the list
print("The total size of the list is: ", npList.nbytes)

The dementions of the list is:  1
The shape of the list is:  (6,)
The size of the list is:  6
The data type of the list is:  int64
The size of each element in the list is:  8
The total size of the list is:  48


# Reshape and 2 D's

In [23]:
print("Reshaped array:\n",npList.reshape((2,3)))
#notice how the array does not change. T
# his is because the reshape function does not change the original array, it returns a new array with the new shape.
print("\nNot reshaped array:\n", npList) 
#of corse you can do this:
reshaped_array = npList.reshape((2,3))
print("\nReshaped array:\n", reshaped_array)

# Flattening an array
flattened_array = reshaped_array.flatten()
print("\nFlattened array:\n", flattened_array)

Reshaped array:
 [[1 2 3]
 [4 5 6]]

Not reshaped array:
 [1 2 3 4 5 6]

Reshaped array:
 [[1 2 3]
 [4 5 6]]

Flattened array:
 [1 2 3 4 5 6]


    Important Note: When using reshape NumPy stores the 2 lists as a copy so changing one will change the other. 

In [24]:
npList = np.array([1, 2, 3, 4, 5, 6])
print("Not reshaped array:\n", npList) 
reshaped_array = npList.reshape((2,3))
print("\nreshaped array:\n", reshaped_array)

#the following will change only 1 time in the list
reshaped_array[0,0]=100
print(npList)

#the will change the whole row
reshaped_array[0]=100
print("\nreshaped array:\n", reshaped_array)

print(npList)

Not reshaped array:
 [1 2 3 4 5 6]

reshaped array:
 [[1 2 3]
 [4 5 6]]
[100   2   3   4   5   6]

reshaped array:
 [[100 100 100]
 [  4   5   6]]
[100 100 100   4   5   6]


In [2]:

two_d = np.array([[1, 2, 3], [4, 5, 6]])
print("2D array:\n", two_d)

#like before you can use np.zeros, np.ones etc wiht (x,y) to create a 2D array
# Creating an array of zeros
# zeros_array = np.zeros((3, 3))
# ones_array = np.ones((2, 4))


# Creating an array with random values
random_array = np.random.random((2, 3))
print("Random array:\n", random_array)

NameError: name 'np' is not defined

# 3 D's
<img src="3.jpg" alt="3.jpg" style="height:300px; width:300px;"/>

Everything is better with 3


In [26]:
array_3d = np.random.randint(0, 10, (3, 3, 3))

print("3D array:\n", array_3d)

three_d = np.array([
    [[5, 78, 2, 34, 0],  
     [7, 80, 4, 36, 2]],
   
    [[5, 78, 2, 34, 0], 
     [6, 79, 3, 35, 1]], 
   
    [[5, 78, 2, 34, 0],
     [7, 80, 4, 36, 2]]]) 

print("\nNumber of dimentions:",three_d.ndim)
print("Shape of the array:",three_d.shape) #(dimentions, rows, columns)
print("Size of the array:",three_d.size)




3D array:
 [[[1 9 7]
  [2 2 5]
  [6 7 2]]

 [[9 0 7]
  [6 1 0]
  [5 7 3]]

 [[3 7 1]
  [3 2 3]
  [0 2 4]]]

Number of dimentions: 3
Shape of the array: (3, 2, 5)
Size of the array: 30


# 4 D's
because why not

In [27]:
array_4d = np.random.randint(0, 10, (2, 3, 2, 5))#(Outer blocks, matrices, rows, columns)

print("4D array:\n", array_4d)
print("\nNumber of dimensions:", array_4d.ndim)
print("Shape of the array:", array_4d.shape)  #
print("Size of the array:", array_4d.size)

four_d = np.array([
    [
        [[5, 78, 2, 34, 0],
         [7, 80, 4, 36, 2]],
        [[5, 79, 2, 34, 0],
         [6, 80, 3, 35, 1]],
        [[5, 81, 2, 34, 0],
         [7, 82, 4, 36, 2]]
    ],
    [
        [[5, 78, 2, 34, 0],
         [7, 80, 4, 36, 2]],
        [[5, 78, 2, 34, 0],
         [6, 79, 3, 35, 1]],
        [[5, 78, 2, 34, 0],
         [7, 80, 4, 36, 2]]
    ]
])

print("\n\nNumber of dimensions:", four_d.ndim)
print("Shape of the array:", four_d.shape)  #
print("Size of the array:", four_d.size)

4D array:
 [[[[6 1 3 2 1]
   [6 2 6 1 4]]

  [[0 0 0 2 2]
   [2 7 7 2 8]]

  [[4 1 6 6 9]
   [4 3 3 6 7]]]


 [[[5 9 1 5 4]
   [6 5 8 1 8]]

  [[7 4 9 4 6]
   [4 5 5 5 4]]

  [[7 1 4 7 5]
   [8 9 4 5 3]]]]

Number of dimensions: 4
Shape of the array: (2, 3, 2, 5)
Size of the array: 60


Number of dimensions: 4
Shape of the array: (2, 3, 2, 5)
Size of the array: 60


# Indexing

In [28]:
#refresh
aList = [1, 2, 3, 4, 5, 6]
print(aList[3:])
#aList=<2

[4, 5, 6]


In [ ]:
print("2D array:\n", two_d)
print("slice the row",two_d[1]) 
print("slice the column",two_d[:,1]) 
print("print the element:", two_d[1,1])

print("\nSliced element of the 4d array:", four_d[0, 1, 1, 1])

NameError: name 'two_d' is not defined

In [49]:
print(two_d[[0,0,1,1,1]]) #prints the first row twice and the second row 3 times

[[1 2 3]
 [1 2 3]
 [4 5 6]
 [4 5 6]
 [4 5 6]]


In [59]:
print("what values are greater than 3:\n",two_d<3)

what values are greater than 3:
 [[ True  True False]
 [False False False]]


In [60]:
print("returning to the two_d will print the values\n",two_d[two_d<3])

returning to the two_d will print the values
 [1 2]


## nan and inf

In [ ]:
inf_list = np.array([0, 1])/np.array([[0],[1]])
print(inf_list)

In [ ]:
print(np.isnan(inf_list))
inf_list[~np.isnan(inf_list)]

In [ ]:
np.mean(inf_list[~np.isnan(inf_list)])

# Matrix Multiplication

In [ ]:
mat_a = np.matrix([0, 3, 5, 5, 5, 2]).reshape(2,3)
mat_b = np.matrix([3, 4, 3, -2, 4, -2]). reshape(3,2)

In [ ]:
mat_a * mat_b

In [ ]:
mat_a @ mat_b

## Stacking

In [ ]:
#Note: the arrays must have the same dimension 
# in the Horizontal  ie (a,b) (a,c)
xArray = np.arange(6).reshape(2,3)
yArray = np.arange(6).reshape(2,3)

zArray= np.vstack((xArray,yArray))
print(zArray)

[[0 1 2]
 [3 4 5]
 [0 1 2]
 [3 4 5]]


In [96]:
#Note: In vertical stacking must have the same dimension
# in the horizontal ie (a,b) (c,b)
xArray = np.arange(8).reshape(4,2)
yArray = np.arange(4,12).reshape(4,2)
zArray = np.hstack((xArray,yArray)) 
print(zArray)


[[ 0  1  4  5]
 [ 2  3  6  7]
 [ 4  5  8  9]
 [ 6  7 10 11]]


## Depth Stacking

In [89]:
print(xArray)
print(yArray)

d_stack = np.dstack((xArray,yArray))
d_stack

[[0 1]
 [2 3]
 [4 5]
 [6 7]]
[[ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]]


array([[[ 0,  4],
        [ 1,  5]],

       [[ 2,  6],
        [ 3,  7]],

       [[ 4,  8],
        [ 5,  9]],

       [[ 6, 10],
        [ 7, 11]]])

## Np Statistics

In [ ]:
print("Maximum value xArray.max():", xArray.max()) 
print("Sum of the array xArray.sum():", xArray.sum())
print("Mean of the array xArray.mean():", xArray.mean()) 

# Variance of the array (measure of spread)
print("Variance xArray.var():", xArray.var())

# Standard deviation of the array (measure of dispersion)
print("Standard deviation xArray.std():", xArray.std())  

Maximum value xArray.max(): 7
Sum of the array xArray.sum(): 28
Mean of the array xArray.mean(): 3.5
Variance xArray.var(): 5.25
Standard deviation xArray.std(): 2.29128784747792


In [100]:
four_d.sum()


1478

In [ ]:
print(xArray)
#four_d.sum(axis=0)# Sum the rows of the 4D array
xArray.sum(axis=0)# Sum the rows of the 2D array


[[0 1]
 [2 3]
 [4 5]
 [6 7]]


array([12, 16])

In [104]:
xArray.sum(axis=1)# colums 

array([ 1,  5,  9, 13])

## How fast is NP?
NP is an amazing tool and is fast at some tasks but a waist at others. so you need to understand when to use it and when not to. 
we will not dig to deep into the math but below are just some examples of the math you can do with NP

In [ ]:
# code provided by NumPy Beginner's Guide - Second Edition, Ivan Idri with minor changes
import timeit
normal_py_sec = timeit.timeit( #use Python range to calculate
    'sum(x*x for x in range(1000))',
    number=10000)

mult_np_sec = timeit.timeit( #use Python multiplication to process np
    'sum(x*x)',
    setup="import numpy as np; x=np.arange(1000)",
    number=10000)

dot_np_sec = timeit.timeit( #use np dot to process 
    'na.dot(x)',
    setup="import numpy as x; x=np.arange(1000)",
    number=10000)

print("Normal Python: %f sec" % normal_py_sec)
print("Mult NumPy: %f sec" % mult_np_sec)
print("Dot NumPy: %f sec" % dot_np_sec)